version: "3"

services:

  prometheus:
    image: prom/prometheus
    container_name: kira-monitor
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml